import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  introductionSidebar: [
    {type: 'autogenerated', dirName: 'getting_started'}
  ],
  deviceDocsSidebar: [
    {type: 'autogenerated', dirName: 'device'}
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
